### PR TITLE
Fix: Double quotes correctly escaped in JS/JSON files (fixes #42)

### LINKED ISSUE #42: Issues around quotes in generated files
I remember seeing oddities with regard to single and double quotes used in input values, and how they get transformed into output files.

Issues found/confirmed:
* Description in rule generator's rule file is HTML-escaped and shouldn't be (but double quotes should be backslash-escaped).
  * Confirmed [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/lib/rules/test-dq.js#L2) and [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/lib/rules/test-dq.js#L14).
* Invalid code snippet in rule generator's test file is HTML-escaped and shouldn't be (but double quotes should be backslash-escaped).
  * Confirmed [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/tests/lib/rules/test-dq.js#L30).
* Description and username in plugin generator's package.json file are HTML-escaped
  * Confirmed [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/package.json#L4) and [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/package.json#L10).
* ~~Single quotes in input are replaced with double quotes throughout. Need to determine if yeoman, our generator code, or something else causes this.~~ Extracted to #44.

Not an issue:
* HTML-escaping of quotes in Markdown files: This is not a problem, see [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/README.md) and [here](https://github.com/platinumazure/eslint-rule-generator-test/blob/master/docs/rules/test-dq.md).
  * ~~Only issue is why single-quotes turn into double-quotes.~~ See #44.

### PR DESCRIPTION
**Pull request by platinumazure**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://github.com/eslint/eslint/blob/master/templates/bug-report.md))
[ ] New rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

See #42.

**Please check each item to ensure your pull request is ready:**

- [x] I've read the [pull request guide](http://eslint.org/docs/developer-guide/contributing/pull-requests)
- [x] I've included tests for my change
- **n/a** I've updated documentation for my change (if appropriate)

**What changes did you make? (Give an overview)**

Throughout the generated file templates, we have used `<%= someVar %>` to interpolate user input into the templates. This uses HTML escaping by default and is not what we want most of the time.

Switching to `<%- someVar %>` prevents HTML escaping, but it leaves vulnerabilities for double quotes when interpolating into JS or JSON strings. So we need to also replace double quotes with backslash escaping.

In the future, it might be better to actually configure the EJS template function (per file) so that the "escape" function is JS double quote escaping, that way we can revert to using the escaped/unescaped interpolation notation for clarity.

**Is there anything you'd like reviewers to focus on?**

I've added some commented out tests for single quote cases, which shouldn't actually be pathological but which are worth testing. Unfortunately, due to some sort of caching in the test generator, new prompt answers aren't respected. For similar reasons I had to duplicate prompts elsewhere (e.g., including a double-quoted username in the test for double-quote description).

Please let me know if anything is unclear.

### CODE REVIEW

File: test/test-creation.js [hunk 1]
```diff
@@ -54,6 +57,96 @@ describe("ESLint Rule Generator", function() {
...
+                });
+
+                it("should have correct description", function() {
+                    assert.strictEqual(this.resultRuleModule.meta.docs.description, "My \"foo\"");
+                });
+            });
+        });
+
+        /*
+         * TODO: (platinumazure) Uncomment when eslint/generator-eslint#44 is
```
Comment (nzakas) [inline test/test-creation.js]: Why not just fix #44 with this PR? I'm not a huge fan of checking in commented out code.

**Comment by platinumazure** [comment]
Because that's a separate issue and I don't know how to fix it yet. That
issue has to do with test configuration. I can remove the commented out
tests if you prefer.

**Comment by nzakas** [comment]
Yeah, just remove the commented out tests. It's really confusing to have commented out code in the repo, especially if we're unsure how long it will take to fix.
